#config_version=6

mode:
  start_events: game_ended, reset_complete
  stop_events: game_start, service_mode_entered
  priority: 10

light_player: 
  mode_attract_started: 
    GI: 
      color: 000000


show_player: 
  mode_attract_started: 
    attract_christmas: 
      key: key_attract_christmas


slide_player: 
  mode_attract_started: 
    attract:
      action: play



