#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ended
  priority: 110

shot_groups: 
  holly_targets:
    shots: holly_h,holly_o,holly_l,holly_l1,holly_y

shots: 
  holly_h:
    switch: s_holly_h
    profile: profile_holly
    start_enabled: True
    show_tokens: 
      lights: l30
      color: de780b
  holly_o:
    switch: s_holly_o
    profile: profile_holly
    start_enabled: True
    show_tokens: 
      lights: l31
      color: de780b
  holly_l:
    switch: s_holly_l
    profile: profile_holly
    start_enabled: True
    show_tokens: 
      lights: l32
      color: de780b
  holly_l1:
    switch: s_holly_l1
    profile: profile_holly
    start_enabled: True
    show_tokens: 
      lights: l33
      color: de780b
  holly_y:
    switch: s_holly_y
    profile: profile_holly
    start_enabled: True
    show_tokens: 
      lights: l34
      color: de780b

show_player: 
  holly_h_hit: 
    flicker_color: 
      key: key_holly_h_hit
      priority: 1
      loops: 2
      speed: 2
      show_tokens: 
        lights: l30
        color: de780b
  holly_o_hit: 
    flicker_color: 
      key: key_holly_o_hit
      priority: 1
      loops: 2
      speed: 2
      show_tokens: 
        lights: l31
        color: de780b
  holly_l_hit: 
    flicker_color: 
      key: key_holly_l_hit
      priority: 1
      loops: 2
      speed: 2
      show_tokens: 
        lights: l32
        color: de780b
  holly_l1_hit: 
    flicker_color: 
      key: key_holly_l1_hit
      priority: 1
      loops: 2
      speed: 2
      show_tokens: 
        lights: l33
        color: de780b
  holly_y_hit: 
    flicker_color: 
      key: key_holly_y_hit
      priority: 1
      loops: 2
      speed: 2
      show_tokens: 
        lights: l34
        color: de780b



