#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ended
  priority: 100

show_player: 
  flash_left_slingshot_red: 
    flicker_color: 
      key: key_s_left_slingshot_active
      loops: 0
      speed: 2
      show_tokens: 
        lights: f141
        color: C81616
  flash_left_slingshot_blue: 
    flicker_color: 
      key: key_s_left_slingshot_active
      loops: 0
      speed: 2
      show_tokens: 
        lights: f141
        color: 1616FF
  flash_right_slingshot_red: 
    flicker_color: 
      key: key_s_right_slingshot_active
      loops: 0
      speed: 2
      show_tokens: 
        lights: f140
        color: C81616
  flash_right_slingshot_blue: 
    flicker_color: 
      key: key_s_right_slingshot_active
      loops: 0
      speed: 2
      show_tokens: 
        lights: f140
        color: 1616FF


light_player: 
  mode_base_started: 
    GI: 
      color: ffffff



slide_player: 
  mode_base_started: 
    base:
      action: play


random_event_player: 
  s_left_slingshot_active: 
    events:
      flash_left_slingshot_red: 1
      flash_left_slingshot_blue: 1
  s_right_slingshot_active: 
    events:
      flash_right_slingshot_red: 1
      flash_right_slingshot_blue: 1



sound_player: 
  flash_left_sling_red: 
    sling_1: 
      action: play
  flash_left_sling_blue: 
    sling_2: 
      action: play
  flash_right_sling_red: 
    sling_2: 
      action: play
  flash_right_sling_blue: 
    sling_1: 
      action: play



