#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ended
  priority: 100

ball_saves: 
  one:
    active_time: 5000ms
    grace_period: 2000ms
    hurry_up_time: 3000ms
    enable_events: ball_save_one
    auto_launch: true
    balls_to_save: -1
  two:
    active_time: 7000ms
    grace_period: 2000ms
    hurry_up_time: 3000ms
    enable_events: ball_save_two
    auto_launch: true
    balls_to_save: -1
  three:
    active_time: 10000ms
    grace_period: 2000ms
    hurry_up_time: 3000ms
    enable_events: ball_save_three
    auto_launch: true
    balls_to_save: -1

event_player: 
  s_popbumper_left_active: 
    - flash_bumper_left
    - flash_bumper_explosion
  s_popbumper_right_active: 
    - flash_bumper_right
    - flash_bumper_explosion
  ball_save_one_saving_ball: 
    - ball_save_saving_ball
  ball_save_two_saving_ball: 
    - ball_save_saving_ball
  ball_save_three_saving_ball: 
    - ball_save_saving_ball
  ball_save_holly_saving_ball: 
    - ball_save_saving_ball
  s_air_duct_active: 
    - show_airduct
    - show_airduct2


light_player: 
  mode_base_started: 
    GI: 
      color: 969696


random_event_player: 
  mode_base_started: 
    events:
      gameplay_music_1: 1
      gameplay_music_2: 1
      gameplay_music_3: 1
      gameplay_music_4: 1
    scope: player
  SpinnerLeft_active: 
    events:
      spinner_fx1: 1
      spinner_fx2: 1
      spinner_fx3: 1
      spinner_fx4: 1
      spinner_fx5: 1
      spinner_fx6: 1
      spinner_fx7: 1
      spinner_fx8: 1
    scope: player
  SpinnerRight_active: 
    events:
      spinner_fx1: 1
      spinner_fx2: 1
      spinner_fx3: 1
      spinner_fx4: 1
      spinner_fx5: 1
      spinner_fx6: 1
      spinner_fx7: 1
      spinner_fx8: 1
    scope: player
  flash_bumper_explosion: 
    events:
      popbumper_fx1: 1
      popbumper_fx2: 1
      popbumper_fx3: 1
    scope: player
  left_orbit_hit: 
    events:
      orbit_fx1: 1
      orbit_fx2: 1
    scope: player
  right_orbit_hit: 
    events:
      orbit_fx1: 1
      orbit_fx2: 1
    scope: player


sequence_shots: 
  left_orbit:
    switch_sequence: 
      - s_left_orbit
      - s_left_orbit2
    sequence_timeout: 1000ms
  right_orbit:
    switch_sequence: 
      - s_right_orbit
      - s_right_orbit2
    sequence_timeout: 1000ms

shots: 
  shoot_again:
    profile: shoot_again
    show_tokens: 
      color: ff0000
    enable_events: ball_save_one_enabled, ball_save_two_enabled, ball_save_three_enabled, ball_save_holly_enabled
    disable_events: ball_save_one_grace_period, ball_save_two_grace_period, ball_save_three_grace_period, ball_save_holly_grace_period
    control_events: 
      - events: ball_save_one_hurry_up, ball_save_two_hurry_up, ball_save_three_hurry_up, ball_save_holly_hurry_up
        state: 1

show_player: 
  s_left_sling_active: 
    flash_sling: 
      key: key_s_left_sling_active
      loops: 1
      show_tokens: 
        lights1: l80
        lights2: l81
        flasher: f141
  s_right_sling_active: 
    flash_sling: 
      key: key_s_right_sling_active
      loops: 1
      show_tokens: 
        lights1: l82
        lights2: l83
        flasher: f140
  SpinnerLeft_active: 
    flicker_color: 
      key: key_s_left_spinner_active
      loops: 0
      speed: 2
      show_tokens: 
        lights: l70
        color: FFFFFF
  SpinnerRight_active: 
    flicker_color: 
      key: key_s_right_spinner_active
      loops: 0
      speed: 2
      show_tokens: 
        lights: l71
        color: FFFFFF
  flash_bumper_explosion: 
    flicker_color: 
      key: key_flash_bumper_explosion
      loops: 0
      speed: 2
      show_tokens: 
        lights: l75
        color: FFFFFF
  flash_bumper_left: 
    flash_left_bumper: 
      key: key_flash_bumper_left
      priority: 1
      loops: 0
      speed: 2
  flash_bumper_right: 
    flash_right_bumper: 
      key: key_flash_bumper_right
      priority: 1
      loops: 0
      speed: 2
  left_orbit_hit: 
    left_orbit: 
      key: key_left_orbit_hit
      priority: 1
      loops: 0
      speed: 2
  right_orbit_hit: 
    right_orbit: 
      key: key_right_orbit_hit
      priority: 1
      loops: 0
      speed: 2
  balldevice_rightvuk_ejecting_ball: 
    flicker_color: 
      key: key_balldevice_rightvuk_ejecting_ball
      priority: 1
      loops: 0
      speed: 4
      show_tokens: 
        lights: f142
        color: 00FF00
  balldevice_bd_plunger_ejecting_ball.10{current_player.saving_ball==1}: 
    swipe_up_red: 
      key: key_balldevice_bd_plunger_ejecting_ball_save
      loops: 0
  show_airduct: 
    flash_color: 
      key: key_airduct_enter_flash
      loops: 3
      show_tokens: 
        lights: AIRDUCT
        color: ffffff
  show_airduct2: 
    airduct: 
      key: key_airduct_enter_show
      loops: 0
  s_captiveball_hit: 
    flicker_color: 
      key: key_captive_ball_hit_flasher
      priority: 1
      loops: 0
      speed: 4
      show_tokens: 
        lights: f143
        color: FFFFFF


slide_player: 
  mode_base_started: 
    base:
      action: play
      expire: 0s
  ball_save_saving_ball: 
    ball_save:
      action: play
      expire: 0s


sound_player: 
  gameplay_music_1: 
    gameplay_music_beethoven: 
      key: main_snd_music
      action: play
  gameplay_music_2: 
    gameplay_music_assault: 
      key: main_snd_music
      action: play
  gameplay_music_3: 
    gameplay_music_finlandia: 
      key: main_snd_music
      action: play
  gameplay_music_4: 
    gameplay_music_battle: 
      key: main_snd_music
      action: play
  s_left_sling_active: 
    sling_1: 
      action: play
  flash_left_sling_blue: 
    sling_2: 
      action: play
  s_right_sling_active: 
    sling_2: 
      action: play
  flash_right_sling_blue: 
    sling_1: 
      action: play
  spinner_fx1: 
    spinner_fx1: 
      action: play
  spinner_fx2: 
    spinner_fx2: 
      action: play
  spinner_fx3: 
    spinner_fx3: 
      action: play
  spinner_fx4: 
    spinner_fx4: 
      action: play
  spinner_fx5: 
    spinner_fx5: 
      action: play
  spinner_fx6: 
    spinner_fx6: 
      action: play
  spinner_fx7: 
    spinner_fx7: 
      action: play
  spinner_fx8: 
    spinner_fx8: 
      action: play
  popbumper_fx1: 
    popbumper_fx1: 
      action: play
  popbumper_fx2: 
    popbumper_fx2: 
      action: play
  popbumper_fx3: 
    popbumper_fx3: 
      action: play
  orbit_fx1: 
    orbit_fx1: 
      action: play
  orbit_fx2: 
    orbit_fx2: 
      action: play


variable_player: 
  s_TrPF1_active: 
    magnets_enabled: 
      action: set_machine
      int: 0

  s_TrPF2_active: 
    magnets_enabled: 
      action: set_machine
      int: 0

  s_TrPF3_active: 
    magnets_enabled: 
      action: set_machine
      int: 0

  s_upper_pf_entrance_active: 
    magnets_enabled: 
      action: set_machine
      int: 1

  ball_save_saving_ball: 
    saving_ball: 
      action: set
      int: 1

  balldevice_bd_plunger_ejecting_ball{current_player.saving_ball==1}: 
    saving_ball: 
      action: set
      int: 0




