#config_version=6

servos:
  servo1:
    number: playfield-4 # vault door
    platform_settings:
      min_us: 650
      max_us: 2500
      home_us: 600
      max_runtime: 3s
    reset_position: 0.1
    reset_events: game_started, ball_ended
    positions:
      0.1: mystery_close_vault
      0.90: mystery_open_vault

  servo2:
    number: playfield-1 # left side wire ramp exit
    platform_settings:
      min_us: 650
      max_us: 2500
      home_us: 600
      max_runtime: 3s
    reset_position: 0.1
    reset_events: game_started, ball_ended
   
      
  servo3:
    number: playfield-2 #nakatomi ball lock
    platform_settings:
      min_us: 650
      max_us: 2500
      home_us: 600
      max_runtime: 3s
    reset_position: 0.1
    reset_events: game_started, ball_ended
  
  servo4:
    number: playfield-3 #nakatomi ball Entrance
    platform_settings:
      min_us: 650
      max_us: 2500
      home_us: 600
      max_runtime: 3s
    reset_position: 0.1
    reset_events: game_started, ball_ended