#config_version=6

shakers: 
  main_shaker:
    number: shakerboard-1
    debug: true
    default_power: 0.5
    control_events:
      skillshot_hit:
        power: 0.250
        duration: 500ms
      s_popbumper_left_active:
        power: 0.250
        duration: 100ms
      s_popbumper_right_active:
        power: 0.250
        duration: 100ms
      s_left_sling_active:
        power: 0.250
        duration: 60ms
      s_right_sling_active:
        power: 0.250
        duration: 60ms
      s_SpinnerLeft_active:
        power: 0.250
        duration: 40ms
      s_Spinnerright_active:
        power: 0.250
        duration: 40ms
      s_captiveball_active:
        power: 0.250
        duration: 300ms