#config_version=6

shot_profiles:
  default:
    states: 
     - name: on
       show: flash
       loops: -1
       speed: 1
       sync_ms: 0
     - name: off
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
  flash_color:
    states: 
     - name: off
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     - name: on
       show: flash_color
       loops: -1
       speed: 1
       sync_ms: 0
  profile_holly:
    states: 
     - name: off
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     - name: on
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
  profile_mystery:
    states: 
     - name: off
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     - name: on
       show: flash_color
       loops: -1
       speed: 3
       sync_ms: 0
  profile_mystery_ho:
    states: 
     - name: off
       show: off
       loops: -1
       speed: 1
       sync_ms: 0
     - name: on
       show: led_color
       loops: 0
       speed: 1
       sync_ms: 0
  profile_bullets:
    advance_on_hit: false
    states: 
     - name: on
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         color: ffffff
     - name: locked_out
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         color: ff0000
     - name: flash
       show: flash_color
       loops: -1
       speed: 4
       sync_ms: 0
       show_tokens: 
         color: ffffff
     - name: complete
       show: led_color
       loops: -1
       speed: 1
       sync_ms: 0
       show_tokens: 
         color: ffff00

