#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ended
  priority: 110

variable_player: 
  s_left_sling_active: 
    score: 
      action: add
      int: 3030

  s_right_sling_active: 
    score: 
      action: add
      int: 3030

  holly_targets_hit: 
    score: 
      action: add
      int: 5000

  SpinnerLeft_active: 
    score: 
      action: add
      int: 1010

  SpinnerRight_active: 
    score: 
      action: add
      int: 1010

  s_popbumper_left_active: 
    score: 
      action: add
      int: 5000

  s_popbumper_right_active: 
    score: 
      action: add
      int: 5000




