#config_version=6

mode:
  start_events: ball_ending{game.tilted == False}
  stop_events: bonus_finished
  priority: 9999
  use_wait_queue: true

event_player: 
  timer_eob_bonus_complete: 
    - bonus_finished
  mode_eob_bonus_started: 
    - stop_main_music1
    - stop_main_music2
    - stop_main_music3
    - stop_main_music4


show_player: 
  mode_eob_bonus_started: 
    eob_bonus: 
      key: key_eob_bonus
      loops: 0


sound_player: 
  stop_main_music1: 
    gameplay_music_beethoven: 
      key: main_snd_music
      action: stop
  stop_main_music2: 
    gameplay_music_assault: 
      key: main_snd_music
      action: stop
  stop_main_music3: 
    gameplay_music_finlandia: 
      key: main_snd_music
      action: stop
  stop_main_music4: 
    gameplay_music_battle: 
      key: main_snd_music
      action: stop


timers: 
  eob_bonus:
    start_value: 0
    end_value: 12
    direction: up
    restart_on_complete: False
    start_running: True
    tick_interval: 1000ms


